import type { DashboardRepository, DashboardSnapshot } from "./dashboard-model";

export const dashboardSnapshot: DashboardSnapshot = {
  projects: [
    {
      id: "commerce-backend",
      name: "E-commerce Backend",
      repository: "github.com/acme/commerce-api",
      branch: "main",
      health: "Healthy",
      requirements: 3,
      tasks: 18,
      blockers: 2,
      updatedAt: "2 minutes ago",
    },
    {
      id: "infra-migration",
      name: "Infrastructure Migration",
      repository: "github.com/acme/platform",
      branch: "release/k8s",
      health: "Needs review",
      requirements: 2,
      tasks: 11,
      blockers: 1,
      updatedAt: "18 minutes ago",
    },
    {
      id: "design-system-v2",
      name: "Design System V2",
      repository: "github.com/acme/interface-kit",
      branch: "next",
      health: "Drafting",
      requirements: 4,
      tasks: 24,
      blockers: 0,
      updatedAt: "1 hour ago",
    },
  ],
  requirements: [
    {
      id: "auth-system",
      title: "User Authentication System",
      source: "requirements/authentication/plan.md",
      status: "Mapped",
      tasks: 7,
      acceptance: 82,
      updatedAt: "Synced 4 minutes ago",
    },
    {
      id: "order-api",
      title: "Order Processing API",
      source: "requirements/orders/spec.md",
      status: "Needs evidence",
      tasks: 6,
      acceptance: 64,
      updatedAt: "Synced 22 minutes ago",
    },
    {
      id: "payments",
      title: "Payment Gateway Integration",
      source: "requirements/payments/roadmap.md",
      status: "Draft",
      tasks: 5,
      acceptance: 38,
      updatedAt: "Imported yesterday",
    },
  ],
  tasks: [
    {
      id: "AUTH-103",
      title: "Implement Password Reset Flow",
      state: "Backlog",
      priority: "P2",
      owner: "codex",
      criteria: 25,
      evidence: 0,
      branch: "feature/password-reset",
      updatedAt: "09:20",
    },
    {
      id: "AUTH-105",
      title: "MFA SMS Delivery Setup",
      state: "Blocked",
      priority: "P0",
      owner: "codex",
      criteria: 42,
      evidence: 1,
      branch: "feature/mfa-sms",
      updatedAt: "09:42",
    },
    {
      id: "AUTH-102",
      title: "OAuth2 Google Integration Setup",
      state: "Ready",
      priority: "P1",
      owner: "codex",
      criteria: 50,
      evidence: 1,
      branch: "feature/google-oauth",
      updatedAt: "10:12",
    },
    {
      id: "AUTH-101",
      title: "Core JWT Validation Service",
      state: "Running",
      priority: "P0",
      owner: "codex",
      criteria: 75,
      evidence: 4,
      branch: "feature/jwt-validation",
      updatedAt: "10:18",
    },
    {
      id: "AUTH-104",
      title: "Database Schema Migration for Users",
      state: "Human Review",
      priority: "P1",
      owner: "reviewer",
      criteria: 91,
      evidence: 5,
      branch: "feature/user-schema",
      updatedAt: "10:27",
    },
    {
      id: "AUTH-100",
      title: "Rate Limiting Middleware",
      state: "Accepted",
      priority: "P1",
      owner: "codex",
      criteria: 100,
      evidence: 7,
      branch: "feature/rate-limit",
      updatedAt: "Yesterday",
    },
  ],
  acceptance: [
    {
      requirement: "JWT tokens reject expired signatures",
      taskId: "AUTH-101",
      taskName: "Core JWT Validation Service",
      status: "Running",
      criteria: 75,
      evidence: "4 files",
    },
    {
      requirement: "MFA enrollment handles provider failures",
      taskId: "AUTH-105",
      taskName: "MFA SMS Delivery Setup",
      status: "Blocked",
      criteria: 42,
      evidence: "1 log",
    },
    {
      requirement: "Admin can audit user access history",
      taskId: "AUTH-104",
      taskName: "Database Schema Migration for Users",
      status: "Human Review",
      criteria: 91,
      evidence: "5 files",
    },
    {
      requirement: "OAuth sign-in preserves account identity",
      taskId: "AUTH-102",
      taskName: "OAuth2 Google Integration Setup",
      status: "Ready",
      criteria: 50,
      evidence: "1 draft",
    },
  ],
  evidence: [
    { kind: "PR", label: "JWT validation implementation", path: "pull/284", status: "Linked" },
    { kind: "Log", label: "Run output for AUTH-101", path: "runs/2026-05-28-auth-101.log", status: "Fresh" },
    { kind: "Test", label: "pytest auth token suite", path: "tests/auth/test_tokens.py", status: "Passed" },
    { kind: "Blocker", label: "SMS provider credentials missing", path: "issues/AUTH-105", status: "Open" },
  ],
  runLog: [
    { time: "10:20:11", level: "info", message: "Preparing isolated worktree for AUTH-105." },
    { time: "10:20:17", level: "ok", message: "Loaded requirement source and acceptance matrix." },
    { time: "10:21:04", level: "info", message: "Installing backend dependencies from lockfile." },
    { time: "10:22:33", level: "warn", message: "SMS provider sandbox key is not configured." },
    { time: "10:23:08", level: "error", message: "Blocked before integration test execution." },
  ],
};

export const mockDashboardRepository: DashboardRepository = {
  async getSnapshot() {
    return dashboardSnapshot;
  },
};
