/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as RequirementsRouteImport } from "./routes/requirements"
import { Route as RefreshRouteImport } from "./routes/refresh"
import { Route as ProjectsRouteImport } from "./routes/projects"
import { Route as MatrixRouteImport } from "./routes/matrix"
import { Route as InsightsRouteImport } from "./routes/insights"
import { Route as BoardRouteImport } from "./routes/board"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as TasksTaskIdRouteImport } from "./routes/tasks.$taskId"
import { Route as RequirementsEmptyRouteImport } from "./routes/requirements.empty"
import { Route as ProjectsRegisterRouteImport } from "./routes/projects.register"
import { Route as ProjectsEmptyRouteImport } from "./routes/projects.empty"
import { Route as BoardInvalidTransitionRouteImport } from "./routes/board.invalid-transition"
import { Route as TasksTaskIdRunRouteImport } from "./routes/tasks.$taskId.run"
import { Route as TasksTaskIdReviewRouteImport } from "./routes/tasks.$taskId.review"
import { Route as TasksTaskIdBlockedRouteImport } from "./routes/tasks.$taskId.blocked"
import { Route as TasksTaskIdAcceptedRouteImport } from "./routes/tasks.$taskId.accepted"
import { Route as RunsTaskIdLogRouteImport } from "./routes/runs.$taskId.log"

const RequirementsRoute = RequirementsRouteImport.update({
  id: "/requirements",
  path: "/requirements",
  getParentRoute: () => rootRouteImport,
} as any)
const RefreshRoute = RefreshRouteImport.update({
  id: "/refresh",
  path: "/refresh",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: "/matrix",
  path: "/matrix",
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: "/insights",
  path: "/insights",
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: "/board",
  path: "/board",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: "/tasks/$taskId",
  path: "/tasks/$taskId",
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsEmptyRoute = RequirementsEmptyRouteImport.update({
  id: "/empty",
  path: "/empty",
  getParentRoute: () => RequirementsRoute,
} as any)
const ProjectsRegisterRoute = ProjectsRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsEmptyRoute = ProjectsEmptyRouteImport.update({
  id: "/empty",
  path: "/empty",
  getParentRoute: () => ProjectsRoute,
} as any)
const BoardInvalidTransitionRoute = BoardInvalidTransitionRouteImport.update({
  id: "/invalid-transition",
  path: "/invalid-transition",
  getParentRoute: () => BoardRoute,
} as any)
const TasksTaskIdRunRoute = TasksTaskIdRunRouteImport.update({
  id: "/run",
  path: "/run",
  getParentRoute: () => TasksTaskIdRoute,
} as any)
const TasksTaskIdReviewRoute = TasksTaskIdReviewRouteImport.update({
  id: "/review",
  path: "/review",
  getParentRoute: () => TasksTaskIdRoute,
} as any)
const TasksTaskIdBlockedRoute = TasksTaskIdBlockedRouteImport.update({
  id: "/blocked",
  path: "/blocked",
  getParentRoute: () => TasksTaskIdRoute,
} as any)
const TasksTaskIdAcceptedRoute = TasksTaskIdAcceptedRouteImport.update({
  id: "/accepted",
  path: "/accepted",
  getParentRoute: () => TasksTaskIdRoute,
} as any)
const RunsTaskIdLogRoute = RunsTaskIdLogRouteImport.update({
  id: "/runs/$taskId/log",
  path: "/runs/$taskId/log",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/board": typeof BoardRouteWithChildren
  "/insights": typeof InsightsRoute
  "/matrix": typeof MatrixRoute
  "/projects": typeof ProjectsRouteWithChildren
  "/refresh": typeof RefreshRoute
  "/requirements": typeof RequirementsRouteWithChildren
  "/board/invalid-transition": typeof BoardInvalidTransitionRoute
  "/projects/empty": typeof ProjectsEmptyRoute
  "/projects/register": typeof ProjectsRegisterRoute
  "/requirements/empty": typeof RequirementsEmptyRoute
  "/tasks/$taskId": typeof TasksTaskIdRouteWithChildren
  "/runs/$taskId/log": typeof RunsTaskIdLogRoute
  "/tasks/$taskId/accepted": typeof TasksTaskIdAcceptedRoute
  "/tasks/$taskId/blocked": typeof TasksTaskIdBlockedRoute
  "/tasks/$taskId/review": typeof TasksTaskIdReviewRoute
  "/tasks/$taskId/run": typeof TasksTaskIdRunRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/board": typeof BoardRouteWithChildren
  "/insights": typeof InsightsRoute
  "/matrix": typeof MatrixRoute
  "/projects": typeof ProjectsRouteWithChildren
  "/refresh": typeof RefreshRoute
  "/requirements": typeof RequirementsRouteWithChildren
  "/board/invalid-transition": typeof BoardInvalidTransitionRoute
  "/projects/empty": typeof ProjectsEmptyRoute
  "/projects/register": typeof ProjectsRegisterRoute
  "/requirements/empty": typeof RequirementsEmptyRoute
  "/tasks/$taskId": typeof TasksTaskIdRouteWithChildren
  "/runs/$taskId/log": typeof RunsTaskIdLogRoute
  "/tasks/$taskId/accepted": typeof TasksTaskIdAcceptedRoute
  "/tasks/$taskId/blocked": typeof TasksTaskIdBlockedRoute
  "/tasks/$taskId/review": typeof TasksTaskIdReviewRoute
  "/tasks/$taskId/run": typeof TasksTaskIdRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/board": typeof BoardRouteWithChildren
  "/insights": typeof InsightsRoute
  "/matrix": typeof MatrixRoute
  "/projects": typeof ProjectsRouteWithChildren
  "/refresh": typeof RefreshRoute
  "/requirements": typeof RequirementsRouteWithChildren
  "/board/invalid-transition": typeof BoardInvalidTransitionRoute
  "/projects/empty": typeof ProjectsEmptyRoute
  "/projects/register": typeof ProjectsRegisterRoute
  "/requirements/empty": typeof RequirementsEmptyRoute
  "/tasks/$taskId": typeof TasksTaskIdRouteWithChildren
  "/runs/$taskId/log": typeof RunsTaskIdLogRoute
  "/tasks/$taskId/accepted": typeof TasksTaskIdAcceptedRoute
  "/tasks/$taskId/blocked": typeof TasksTaskIdBlockedRoute
  "/tasks/$taskId/review": typeof TasksTaskIdReviewRoute
  "/tasks/$taskId/run": typeof TasksTaskIdRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/board"
    | "/insights"
    | "/matrix"
    | "/projects"
    | "/refresh"
    | "/requirements"
    | "/board/invalid-transition"
    | "/projects/empty"
    | "/projects/register"
    | "/requirements/empty"
    | "/tasks/$taskId"
    | "/runs/$taskId/log"
    | "/tasks/$taskId/accepted"
    | "/tasks/$taskId/blocked"
    | "/tasks/$taskId/review"
    | "/tasks/$taskId/run"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/board"
    | "/insights"
    | "/matrix"
    | "/projects"
    | "/refresh"
    | "/requirements"
    | "/board/invalid-transition"
    | "/projects/empty"
    | "/projects/register"
    | "/requirements/empty"
    | "/tasks/$taskId"
    | "/runs/$taskId/log"
    | "/tasks/$taskId/accepted"
    | "/tasks/$taskId/blocked"
    | "/tasks/$taskId/review"
    | "/tasks/$taskId/run"
  id:
    | "__root__"
    | "/"
    | "/board"
    | "/insights"
    | "/matrix"
    | "/projects"
    | "/refresh"
    | "/requirements"
    | "/board/invalid-transition"
    | "/projects/empty"
    | "/projects/register"
    | "/requirements/empty"
    | "/tasks/$taskId"
    | "/runs/$taskId/log"
    | "/tasks/$taskId/accepted"
    | "/tasks/$taskId/blocked"
    | "/tasks/$taskId/review"
    | "/tasks/$taskId/run"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRouteWithChildren
  InsightsRoute: typeof InsightsRoute
  MatrixRoute: typeof MatrixRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RefreshRoute: typeof RefreshRoute
  RequirementsRoute: typeof RequirementsRouteWithChildren
  TasksTaskIdRoute: typeof TasksTaskIdRouteWithChildren
  RunsTaskIdLogRoute: typeof RunsTaskIdLogRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/requirements": {
      id: "/requirements"
      path: "/requirements"
      fullPath: "/requirements"
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/refresh": {
      id: "/refresh"
      path: "/refresh"
      fullPath: "/refresh"
      preLoaderRoute: typeof RefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/projects": {
      id: "/projects"
      path: "/projects"
      fullPath: "/projects"
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/matrix": {
      id: "/matrix"
      path: "/matrix"
      fullPath: "/matrix"
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/insights": {
      id: "/insights"
      path: "/insights"
      fullPath: "/insights"
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/board": {
      id: "/board"
      path: "/board"
      fullPath: "/board"
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/tasks/$taskId": {
      id: "/tasks/$taskId"
      path: "/tasks/$taskId"
      fullPath: "/tasks/$taskId"
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/requirements/empty": {
      id: "/requirements/empty"
      path: "/empty"
      fullPath: "/requirements/empty"
      preLoaderRoute: typeof RequirementsEmptyRouteImport
      parentRoute: typeof RequirementsRoute
    }
    "/projects/register": {
      id: "/projects/register"
      path: "/register"
      fullPath: "/projects/register"
      preLoaderRoute: typeof ProjectsRegisterRouteImport
      parentRoute: typeof ProjectsRoute
    }
    "/projects/empty": {
      id: "/projects/empty"
      path: "/empty"
      fullPath: "/projects/empty"
      preLoaderRoute: typeof ProjectsEmptyRouteImport
      parentRoute: typeof ProjectsRoute
    }
    "/board/invalid-transition": {
      id: "/board/invalid-transition"
      path: "/invalid-transition"
      fullPath: "/board/invalid-transition"
      preLoaderRoute: typeof BoardInvalidTransitionRouteImport
      parentRoute: typeof BoardRoute
    }
    "/tasks/$taskId/run": {
      id: "/tasks/$taskId/run"
      path: "/run"
      fullPath: "/tasks/$taskId/run"
      preLoaderRoute: typeof TasksTaskIdRunRouteImport
      parentRoute: typeof TasksTaskIdRoute
    }
    "/tasks/$taskId/review": {
      id: "/tasks/$taskId/review"
      path: "/review"
      fullPath: "/tasks/$taskId/review"
      preLoaderRoute: typeof TasksTaskIdReviewRouteImport
      parentRoute: typeof TasksTaskIdRoute
    }
    "/tasks/$taskId/blocked": {
      id: "/tasks/$taskId/blocked"
      path: "/blocked"
      fullPath: "/tasks/$taskId/blocked"
      preLoaderRoute: typeof TasksTaskIdBlockedRouteImport
      parentRoute: typeof TasksTaskIdRoute
    }
    "/tasks/$taskId/accepted": {
      id: "/tasks/$taskId/accepted"
      path: "/accepted"
      fullPath: "/tasks/$taskId/accepted"
      preLoaderRoute: typeof TasksTaskIdAcceptedRouteImport
      parentRoute: typeof TasksTaskIdRoute
    }
    "/runs/$taskId/log": {
      id: "/runs/$taskId/log"
      path: "/runs/$taskId/log"
      fullPath: "/runs/$taskId/log"
      preLoaderRoute: typeof RunsTaskIdLogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BoardRouteChildren {
  BoardInvalidTransitionRoute: typeof BoardInvalidTransitionRoute
}

const BoardRouteChildren: BoardRouteChildren = {
  BoardInvalidTransitionRoute: BoardInvalidTransitionRoute,
}

const BoardRouteWithChildren = BoardRoute._addFileChildren(BoardRouteChildren)

interface ProjectsRouteChildren {
  ProjectsEmptyRoute: typeof ProjectsEmptyRoute
  ProjectsRegisterRoute: typeof ProjectsRegisterRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsEmptyRoute: ProjectsEmptyRoute,
  ProjectsRegisterRoute: ProjectsRegisterRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface RequirementsRouteChildren {
  RequirementsEmptyRoute: typeof RequirementsEmptyRoute
}

const RequirementsRouteChildren: RequirementsRouteChildren = {
  RequirementsEmptyRoute: RequirementsEmptyRoute,
}

const RequirementsRouteWithChildren = RequirementsRoute._addFileChildren(
  RequirementsRouteChildren,
)

interface TasksTaskIdRouteChildren {
  TasksTaskIdAcceptedRoute: typeof TasksTaskIdAcceptedRoute
  TasksTaskIdBlockedRoute: typeof TasksTaskIdBlockedRoute
  TasksTaskIdReviewRoute: typeof TasksTaskIdReviewRoute
  TasksTaskIdRunRoute: typeof TasksTaskIdRunRoute
}

const TasksTaskIdRouteChildren: TasksTaskIdRouteChildren = {
  TasksTaskIdAcceptedRoute: TasksTaskIdAcceptedRoute,
  TasksTaskIdBlockedRoute: TasksTaskIdBlockedRoute,
  TasksTaskIdReviewRoute: TasksTaskIdReviewRoute,
  TasksTaskIdRunRoute: TasksTaskIdRunRoute,
}

const TasksTaskIdRouteWithChildren = TasksTaskIdRoute._addFileChildren(
  TasksTaskIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRouteWithChildren,
  InsightsRoute: InsightsRoute,
  MatrixRoute: MatrixRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RefreshRoute: RefreshRoute,
  RequirementsRoute: RequirementsRouteWithChildren,
  TasksTaskIdRoute: TasksTaskIdRouteWithChildren,
  RunsTaskIdLogRoute: RunsTaskIdLogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
